/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401xe.h"


//create function to wait for a specified amount of time
void delayTime(int moment)
{
	volatile int i,j;
	for(i=0;i<moment;++i)
	{
		j++;
	}
}


int main(void)
{
    /* Loop forever */
	//Enable the GPIO clock for Port C using the AHB and RCC
	RCC->AHB1ENR|=RCC_AHB1ENR_GPIOCEN;		//1U<<2


	//Set any control registers for PORTC Pin6

	//MODE REGISTER - SET PIN6 TO OUTPUT MODE- 01
	GPIOC->MODER &=~(GPIO_MODER_MODER6_1);
	GPIOC->MODER |=GPIO_MODER_MODER6_0;

	//OTYPE REGISTER
	GPIOC->OTYPER &=~(GPIO_OTYPER_OT6);

	//OSPEED REGISTER
	GPIOC->OSPEEDR |=GPIO_OSPEEDER_OSPEEDR6;

	//PUPDR REGISTER
	GPIOC->PUPDR&=~(GPIO_PUPDR_PUPDR6);

	while(1)

	{
		//Turn ON LED
		//BSRR REGISTER TO SET THE BIT
		GPIOC->BSRR |=GPIO_BSRR_BS6;	//or (1U<<6)
		//wait
		delayTime(1000000);

		//Turn OFF LED
		//BRR REGISTER TO RESET THE BIT
		GPIOC->BSRR |=GPIO_BRR_BR6;		//or (iU<<22)
		//wait
		delayTime(1000000);

	}




	for(;;);
}
